### ISSUE TITLE
Déploiement sur GitHub pages impossible depuis un fork

### ISSUE THREAD

**Issue by Slipknot32** [LordThi/babybirthgames#6]
https://github.com/Slipknot32/babybirthgames voici le fork du projet. 

Le lancement du projet fonctionne parfaitement en local, pas d'erreur de build, mais quand je souhaite faire un déploiement de la branche Main, je n'ai pas d'erreur de déploiement mais quand je suis l'URL, ce dernier me renvoie sur le README.md et n'affiche pas le projet. 
Existe t-il une façons de faire pour que le déploiement ce fasse dans le dossier /app ? 

![image](https://github.com/LordThi/babybirthgames/assets/47857591/af624140-f9e4-4b02-ab5b-9c3a8e8e1bf1)

**Comment by Slipknot32** [comment]
UPDATE: le problème a été régler dans mon cas quand j'ai modifier dans le fichier jsconfig.json le code suivant : 
![image](https://github.com/LordThi/babybirthgames/assets/47857591/f59b8bc8-7387-467f-b678-3c620ca83571)

en ce code, pour cibler le dossier "source" comme étant app : 
![image](https://github.com/LordThi/babybirthgames/assets/47857591/e4dbd048-cfee-49c7-9cae-c38056b591c0)

**Comment by LordThi** [comment]
étrange, car justement le `/`* signifie "tout ce qui est derrière` /` " Mais tant mieux si le problème a été résolu :)
